image: python

stages:
- lint
- test

before_script:
- curl -O https://bootstrap.pypa.io/get-pip.py
- python get-pip.py
- pip install -r requirements.txt

after_script:
- pip install codecov
- codecov --token=$CODECOV_TOKEN

pylama:
  image: python:3.6
  stage: test
  script: tox -e linters

isort:
  image: python:3.6

python34:
  image: python:3.4
  stage: test
  script: tox -e py34

python35:
  image: python:3.5
  stage: test
  script: tox -e py35

python36:
  image: python:3.6
  stage: test
  script: tox -e py36

python37:
  image: python:3.7
  stage: test
  script: tox -e py37

